#!/bin/bash

short_head ()
{
    rev=`git rev-list HEAD...HEAD^1`
    echo ${rev:0:8}
} 

pull_and_tar ()
{
    git_dir=$1
    tar_prefix=$2

    echo Working on ${git_dir}

    cd $git_dir
    git pull
    dname=${tar_prefix}-git`short_head`

    rm -f ../${dname}.tar{,.bz2}
    echo -e "\tMaking ${dname}.tar"
    git archive --format=tar -o ../${dname}.tar --prefix=${dname}/ HEAD ./
    cd ..

    echo -e "\tbzipping archive"
    bzip2 ${dname}.tar
}

pull_and_tar tic6x-binutils binutils-2.20-tic64x
pull_and_tar llvm-tic6x llvm-2.6-tic64x
